
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sbh: <http://wiki.synbiohub.org/wiki/Terms/synbiohub#>
PREFIX sbol: <http://sbols.org/v2#>

INSERT {
    <$topLevel> sbol:attachment <$attachmentURI> .

    <$collectionUri> sbol:member <$attachmentURI> .

    <$attachmentURI> a sbol:Attachment ;
        dcterms:title $name ;
        dcterms:description $description ;
        sbol:displayId $displayId ;
        sbol:persistentIdentity <$persistentIdentity> ;
        sbol:version $version ;
	sbh:ownedBy <$ownedBy> ;
	sbh:topLevel <$attachmentURI> ;
        sbol:source <$attachmentSource> ;
        sbol:hash $hash ;
        sbol:size $size ;
        sbol:format <$type> .

}

