PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sbh: <http://wiki.synbiohub.org/wiki/Terms/synbiohub#>
PREFIX intbio: <http://intbio.ncl.ac.uk#>
PREFIX sbol: <http://sbols.org/v2#>
PREFIX dcterms: <http://purl.org/dc/terms/>

INSERT DATA {
    $uri a intbio:Test ;
    	sbol:displayId $displayId ;
    	sbol:persistentIdentity $persistentIdentity ;
    	sbol:version $version ;
    	dcterms:title $displayId ;
    	sbh:ownedBy <$ownedBy> ;
    	intbio:testFor $testFor .
} 


