PREFIX sbol2: <http://sbols.org/v2#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX synbiohub: <http://synbiohub.org#>

SELECT 
       ?persistentIdentity
       ?displayId 
       ?version
       ?name
       ?description
       ?purpose
       ?chassis 
       ?uploadedBy
WHERE { 
      <$collection> a sbol2:Collection .
      OPTIONAL { <$collection> sbol2:persistentIdentity ?persistentIdentity . }
      OPTIONAL { <$collection> sbol2:displayId ?displayId . }
      OPTIONAL { <$collection> sbol2:version ?version . }
      OPTIONAL { <$collection> dcterms:title ?name . }
      OPTIONAL { <$collection> dcterms:description ?description . }
      OPTIONAL { <$collection> synbiohub:purpose ?purpose . }
      OPTIONAL { <$collection> synbiohub:chassis ?chassis . }
      OPTIONAL { <$collection> synbiohub:uploadedBy ?uploadedBy . }
}