PREFIX sbol2: <http://sbols.org/v2#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?uri 
       ?displayId
       ?name
       ?description
       ?type
$graphs 
WHERE { {
SELECT DISTINCT ?uri 
       ?displayId
       ?name
       ?description
       ?type
$graphs
WHERE { 
<$collection> a sbol2:Collection .
<$collection> sbol2:member ?uri .
OPTIONAL { ?uri a ?type . }
OPTIONAL { ?uri sbol2:displayId ?displayId . }
OPTIONAL { ?uri dcterms:title ?name . }
OPTIONAL { ?uri dcterms:description ?description . }
$search
}
$sort
}}
$limit
$offset
