PREFIX sbol2: <http://sbols.org/v2#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX synbiohub: <http://synbiohub.org#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX sbh: <http://wiki.synbiohub.org/wiki/Terms/synbiohub#>

SELECT 
       ?persistentIdentity
       ?displayId 
       ?version
       ?name
       ?description
       ?ownedBy
       ?mutableDescription
       ?mutableNotes
       ?mutableProvenance
       ?creator
       ?created
       ?modified
       ?wasDerivedFrom
       ?wasGeneratedBy
WHERE { 
      OPTIONAL { <$collection> sbol2:persistentIdentity ?persistentIdentity . }
      OPTIONAL { <$collection> sbol2:displayId ?displayId . }
      OPTIONAL { <$collection> sbol2:version ?version . }
      OPTIONAL { <$collection> dcterms:title ?name . }
      OPTIONAL { <$collection> dcterms:description ?description . }
      OPTIONAL { <$collection> dc:creator ?creator . }
      OPTIONAL { <$collection> dcterms:created ?created . }
      OPTIONAL { <$collection> dcterms:modified ?modified . }
      OPTIONAL { <$collection> synbiohub:uploadedBy ?uploadedBy . }
      OPTIONAL { <$collection> sbh:ownedBy ?ownedBy . }
      OPTIONAL { <$collection> sbh:mutableDescription ?mutableDescription . }
      OPTIONAL { <$collection> sbh:mutableNotes ?mutableNotes . }
      OPTIONAL { <$collection> sbh:mutableProvenance ?mutableProvenance . }
      OPTIONAL { <$collection> prov:wasDerivedFrom ?wasDerivedFrom . }
      OPTIONAL { <$collection> prov:wasGeneratedBy ?wasGeneratedBy . }
}
