PREFIX sbol2: <http://sbols.org/v2#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX ncbi: <http://www.ncbi.nlm.nih.gov#>
PREFIX synbiohub: <http://synbiohub.org#>
PREFIX sbh: <http://wiki.synbiohub.org/wiki/Terms/synbiohub#>
PREFIX igem: <http://wiki.synbiohub.org/wiki/Terms/igem#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

select (sum(?tempcount) as ?count) WHERE {
{
    SELECT (count(distinct ?subject) as ?tempcount)
    $from
    WHERE {
        $criteria

        ?subject sbh:topLevel ?subject .
        OPTIONAL { ?subject sbol2:displayId ?displayId . }		 
        OPTIONAL { ?subject dcterms:title ?name . }		 
        OPTIONAL { ?subject dcterms:description ?description . }	
    }
}
}
