PREFIX sbol2: <http://sbols.org/v2#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX ncbi: <http://www.ncbi.nlm.nih.gov#>

SELECT ?Collection ?name ?description ?displayId ?version WHERE {
    ?Collection a sbol2:Collection .
    $parentCollection sbol2:member ?Collection .
    OPTIONAL { ?Collection dcterms:title ?name . }
    OPTIONAL { ?Collection sbol2:displayId ?displayId . }
    OPTIONAL { ?Collection dcterms:description ?description . }
    OPTIONAL { ?Collection sbol2:version ?version }
    FILTER NOT EXISTS { $parentCollection sbol2:member ?otherCollection . ?otherCollection sbol2:member ?Collection }
}
