PREFIX dcterms: <http://purl.org/dc/terms/>

DELETE WHERE {
    <$topLevel> dcterms:source ?source .
}
;
DELETE WHERE {
    <$topLevel> dcterms:modified ?modified .
}
;
INSERT DATA {
    <$topLevel> dcterms:source $source .
    <$topLevel> dcterms:modified $modified .
} 


