PREFIX dcterms: <http://purl.org/dc/terms/>

DELETE WHERE {
    <$subject> <$predicate> ?o
}
;
DELETE WHERE {
    <$subject> dcterms:modified ?mod
}
;
INSERT DATA {
    <$subject> <$predicate> $object .
    <$subject> dcterms:modified $modified
}
