PREFIX dcterms: <http://purl.org/dc/terms/>

DELETE {
    <$subject> <$predicate> ?o .
    <$subject> dcterms:modified ?mod
}

INSERT {
    <$subject> <$predicate> $object .
    <$subject> dcterms:modified $modified
}

WHERE {
    <$subject> <$predicate> ?o .
    OPTIONAL {
        <$subject> dcterms:modified ?mod
    }
}
